fixing warnings

diff --git a/vignettes/Makefile b/vignettes/Makefile
--- a/vignettes/Makefile
+++ b/vignettes/Makefile
@@ -20,10 +20,12 @@ all:
 	make synapter
 	make clean
 
-setvars:
-ifeq (${R_HOME},)
-R_HOME=	$(shell R RHOME)
-endif
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+
 
 synapter: 
 	"$(R_HOME)/bin/R" CMD pdflatex synapter.tex
